
household_power_consumption <- read.csv("C:/Users/hryut/OneDrive/Documents/R Projects/Coursera-DS-4-WK1/household_power_consumption.txt", sep=";", na.strings="?")
household_power_consumption$Date <- as.Date(household_power_consumption$Date, "%d/%m/%Y")
x <-Paste(household_power_consumption$Date, household_power_consumption$Time)
household_power_consumption$DateTime <- strptime(x, "%Y-%m-%d %T")
d <- subset(household_power_consumption, household_power_consumption$Date == "2007-02-01" | household_power_consumption$Date == "2007-02-02")
par(mfrow = c(2,2))
plot(d$DateTime, d$Global_active_power, type="n",ylab = "Global Active Power", xlab = NA)
 lines(d$DateTime, d$Global_active_power)
plot(d$DateTime, d$Voltage, type="n",ylab = "voltage", xlab = "datetime")
 lines(d$DateTime, d$Voltage)
plot(d$DateTime, d$Sub_metering_1, xlab=NA, ylab="Energy Sub metering",lty=1, lwd=1, pch=".", type="n")
 lines(d$DateTime, d$Sub_metering_1, lty=1, lwd=1, pch=".")
 lines(d$DateTime, d$Sub_metering_2, lty=1, lwd=1, pch=".", col="red")
 lines(d$DateTime, d$Sub_metering_3, lty=1, lwd=1, pch=".", col="blue")
 legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.7, lty=1, col=c("black","red","blue"))
plot(d$DateTime, d$Global_reactive_power, type="n",ylab = "Global Reactive Power", xlab = "datetime")
 lines(d$DateTime, d$Global_reactive_power)
dev.copy(png,"plot4.png", width=480, height=480, type="windows")
dev.off()

